# Generated by Django 2.2.16 on 2022-06-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220620_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='D',
            new_name='post',
        ),
    ]
